# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'MagicalRecord'
  pod 'CacheTracker/CoreData'
  pod 'CacheTrackerConsumer', :path => ‘./..’
  pod 'CacheTrackerConsumer/UIKit', :path => ‘./..’

  target 'CacheTrackerSectionedConsumerTests' do
    inherit! :search_paths
  end

end
